"""add task operation users relationship

Revision ID: 020234d98fce
Revises: 6f3741e2e473
Create Date: 2026-01-05 16:54:40.924604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020234d98fce'
down_revision: Union[str, Sequence[str], None] = '6f3741e2e473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date_established', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('company_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('company_pkey'))
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('task_type', postgresql.ENUM('SOLO', 'GROUP', name='tasktype'), autoincrement=False, nullable=False),
    sa.Column('payment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', postgresql.ENUM('ALMATY', 'ASTANA', 'SHYMKENT', 'KARAGANDA', 'AKTOBE', 'TARAZ', 'PAVLODAR', 'OSKEMEN', 'SEMEY', 'KOSTANAY', 'KYZYLORDA', 'ATYRAU', 'ORAL', 'PETROPAVL', 'TURKISTAN', name='city'), autoincrement=False, nullable=True),
    sa.Column('task_step', postgresql.ENUM('AVAILABLE', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'FAILED', name='taskstep'), autoincrement=False, nullable=False),
    sa.Column('completed_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('verified_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('task_pkey'))
    )
    # ### end Alembic commands ###
