"""Creating Task Point History table and fixing some tables

Revision ID: 30687e5b5a58
Revises: 7db1636b0048
Create Date: 2026-02-04 15:47:12.710564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30687e5b5a58'
down_revision: Union[str, Sequence[str], None] = '7db1636b0048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # handled by final ensure_schema migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_statistic', 'total_points')
    op.drop_column('task', 'quality_status')
    sa.Enum(name='qualitystatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
