"""change nullable status in TaskHistoryPoints

Revision ID: 4e9b1bfe1ede
Revises: 65ff57bdbae6
Create Date: 2026-03-15 23:47:00.467628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9b1bfe1ede'
down_revision: Union[str, Sequence[str], None] = '65ff57bdbae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE task_point_history ALTER COLUMN calculated_at DROP NOT NULL;
        EXCEPTION WHEN undefined_table THEN NULL;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_point_history', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
