"""rewriting of task history models

Revision ID: 65966c540824
Revises: a2463cd91071
Create Date: 2026-02-20 14:36:53.347530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65966c540824'
down_revision: Union[str, Sequence[str], None] = 'a2463cd91071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('difficulty_config')
    op.drop_index(op.f('idx_tph_finalized'), table_name='task_point_history')
    op.drop_index(op.f('idx_tph_task'), table_name='task_point_history')
    op.drop_index(op.f('idx_tph_user_period'), table_name='task_point_history')
    op.drop_table('task_point_history')
    op.create_index('idx_user_period', 'user_statistic', ['user_id', 'period_type', 'period_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_period', table_name='user_statistic')
    op.create_table('task_point_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('base_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rank', postgresql.ENUM('S', 'A', 'B', 'C', name='rank'), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completed_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quality_status', postgresql.ENUM('VERIFIED', 'FAILED', name='qualitystatus'), autoincrement=False, nullable=False),
    sa.Column('delay_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deadline_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('success_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('preliminary_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_finalized', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finalized_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('task_point_history_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('task_point_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_point_history_pkey'))
    )
    op.create_index(op.f('idx_tph_user_period'), 'task_point_history', ['user_id', 'period_date'], unique=False)
    op.create_index(op.f('idx_tph_task'), 'task_point_history', ['task_id'], unique=False)
    op.create_index(op.f('idx_tph_finalized'), 'task_point_history', ['is_finalized', 'period_date'], unique=False)
    op.create_table('difficulty_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('low_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medium_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('difficulty_config_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('difficulty_config_pkey')),
    sa.UniqueConstraint('company_id', name=op.f('difficulty_config_company_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
