"""restore company and update user model

Revision ID: 6d0bbc35bd85
Revises: 21a9fb3ecd9c
Create Date: 2026-01-10 19:52:46.403690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0bbc35bd85'
down_revision: Union[str, Sequence[str], None] = '21a9fb3ecd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'company_id')
    # ### end Alembic commands ###
