"""change nullable status in TaskHistoryPoints

Revision ID: 7715c54bb51f
Revises: bbbbbbbbbbbb
Create Date: 2026-03-20 00:00:51.286029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7715c54bb51f'
down_revision: Union[str, Sequence[str], None] = 'bbbbbbbbbbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
