"""change nullable status in TaskHistoryPoints

Revision ID: 7c09d1d7f3f6
Revises: 4e9b1bfe1ede
Create Date: 2026-03-16 00:03:17.137329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c09d1d7f3f6'
down_revision: Union[str, Sequence[str], None] = '4e9b1bfe1ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$ BEGIN
            UPDATE task_point_history SET calculated_at = created_at WHERE calculated_at IS NULL;
        EXCEPTION WHEN undefined_table THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE task_point_history ALTER COLUMN calculated_at SET NOT NULL;
        EXCEPTION WHEN undefined_table THEN NULL;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_point_history', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
