"""create company table

Revision ID: 8fcaacc78baf
Revises: 0b1a49445252
Create Date: 2025-12-23 18:44:18.993928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcaacc78baf'
down_revision: Union[str, Sequence[str], None] = '0b1a49445252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_position_name'), 'position', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_name'), table_name='position')
    # ### end Alembic commands ###
