"""Debug

Revision ID: ac8c02b7e3ec
Revises: ae50dd9523ae
Create Date: 2026-01-03 19:00:10.381262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac8c02b7e3ec'
down_revision: Union[str, Sequence[str], None] = 'ae50dd9523ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_executor_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'executor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('executor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_executor_id_fkey', 'task', 'user', ['executor_id'], ['id'])
    # ### end Alembic commands ###
