"""bonus added to user

Revision ID: c60780fa9f8c
Revises: c86e0c846e64
Create Date: 2026-01-28 14:35:40.847722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60780fa9f8c'
down_revision: Union[str, Sequence[str], None] = 'c86e0c846e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bonus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bonus')
    # ### end Alembic commands ###
