"""add corrections

Revision ID: c86e0c846e64
Revises: 935a7087f9a9
Create Date: 2026-01-12 23:33:28.536467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86e0c846e64'
down_revision: Union[str, Sequence[str], None] = '935a7087f9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'company_id')
    # ### end Alembic commands ###
